### ISSUE TITLE
Querrying multiple journals at the same time

### ISSUE THREAD

**Issue by PeterGrabitz** [Rekyt/rromeo#25]
Currently rr_journal_name allows for querrying one single journal.  Is there any plan to allow for querrying multiple journals at the same time? 
Something like:
rromeo::rr_journal_names( c("Journal of Biogeography", "PLOS one"), qtype = "exact")

**Comment by Rekyt** [comment]
Hi @PeterGrabitz,
Thank you for your interest! It is a great suggestion.
We implemented your suggestion on branch `multiple_journal_names` through commit be5dd83.
However, as we still struggle to provide automated testing for this function, it is not yet in the master branch.

For the moment you can install this unstable & untested version using:
```r
remotes::install_github("Rekyt/rromeo@multiple_journal_names")
```

Do no hesitate if you have any additional comments and/or suggestions on `rromeo` ;)

**Comment by Rekyt** [comment]
@PeterGrabitz you can now use multiple inputs for `rr_journal_name()` `rr_journal_issn()` and `rr_publisher()` with the last development version of `rromeo`.
