### ISSUE TITLE
Bug Using specific ISSN

### ISSUE THREAD

**Issue by PeterGrabitz** [Rekyt/rromeo#28]
Querrying  "0732-183X" returns 

> Error: 'If required by institution policy or funding agency policy' does not exist in current working directory ('C:/WORKINGDIRECTORY').

It also stops batch searches. 
This is another Error:

> Error:` 'If required by institution policy or funding agency policy' does not exist in current working directory ('C:/WORKINGDIRECTORY').

It seems like there are some problems with the " Restrictions" field.

**Comment by Rekyt** [comment]
Hi @PeterGrabitz,
It was indeed a problem when trying to parse the embargo period of journals.
It is now fixed so install the latest development version and reload to package.
