### ISSUE TITLE
Remaining SHERPA/RoMEO functions to add

### ISSUE THREAD

**Issue by Rekyt** [Rekyt/rromeo#6]
What do we want to add?

* `rr_colour()` or `rr_color()` According to the API doc, we can query the API by SHERPA/RoMEO colour, we could add this
* `rr_country()` to retrieve publisher data by country? Maybe to check if publishing pratices differ by country
* Also parse better the conditions when restrictions apply on the archival of pre-print, post-print and publisher's manuscript

**Comment by Bisaloo** [comment]
No, the cap is lifted in this case: http://www.sherpa.ac.uk/romeo/api29.php?colour=yellow&showfunder=none (when `<apicontrol>colour</apicontrol>`)

**Comment by Rekyt** [comment]
Then it is still relevant IMHO

**Comment by Rekyt** [comment]
One function we haven't added yet is the search by publisher name function which could be:
`rr_publisher_name()` in contrast with current `rr_publisher() that could become `rr_publisher_id()`

**Comment by Rekyt** [comment]
Also there are functions to retrieve publisher by country which could be `rr_publisher_country()` and by continent `rr_publisher_continent()`
finally there is an option to retrieve all publishers so why not `rr_publisher_all()` with a message that it can take long to retrieve all publishers.
