### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by Rekyt** [Rekyt/rromeo#7]
To ensure that the package is working well, we could use package[`vcr`](https://github.com/ropensci/vcr) to mimic HTTP requests and check that functions work as expected.

**Comment by Bisaloo** [comment]
I'm interesting in learning more about this so you can assign this issue to me if that's okay with you.

**Comment by Bisaloo** [comment]
You've probably seen [this relevant blog post](https://itsalocke.com/blog/packages-for-testing-your-r-package/).

**Comment by Rekyt** [comment]
There is also [this amazing book](https://ropensci.github.io/http-testing-book/) by Scott Chamberlain ;)
